version: '3.8'

services:
  backend:
    build: ./
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      spring.profiles.active: prod
      server.host: localhost
      spring.datasource.url: jdbc:mysql://db:3306/http-monitoring
      spring.datasource.username: user_example # should be done secretly by some secret or env
      spring.datasource.password: password_example # should be done secretly by some secret or env

  db:
    image: mysql:8
    restart: unless-stopped
#    ports:
#      - "3306:3306"
    environment:
      MYSQL_USER: user_example # should be done secretly by some secret or env
      MYSQL_PASSWORD: password_example # should be done secretly by some secret or env
      MYSQL_DATABASE: http-monitoring
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
#    volumes:
#      - "./db_data:/var/lib/mysql"